auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: 192.168.1.1:9090
    name: alpha
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.1.2:9090
    name: dev
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.1.3:9090
    name: preprod
    properties: {}
    readOnly: false
rbac:
  roles: []
